name: coupons
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  google_sign_in:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_bloc: ^5.0.1
  equatable: ^1.2.2
  page_transition: ^1.1.7+6
  native_progress_hud: ^1.0.5
  string_validator: ^0.1.4
  url_launcher: ^5.5.0
  mailer2: ^1.2.5
  launch_review: ^2.0.0
  shared_preferences: ^0.5.8
  share: ^0.6.4+3
  firebase_core: ^0.6.0
  firebase_database: ^5.0.0
  firebase_auth: ^0.19.0+1
  firebase_analytics: ^5.0.16
  flutter_launcher_icons: ^0.7.5
  cloud_firestore: ^0.15.0



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  
  assets:
    - ./lib/assets/img/

  fonts:
    - family: pr_en_bold
      fonts:
        - asset: ./lib/assets/fonts/en/pr_bold.otf

    - family: pr_en_reg
      fonts:
        - asset: ./lib/assets/fonts/en/pr_regular.otf

    - family: pr_ar_reg
      fonts:
        - asset: ./lib/assets/fonts/ar/pr_ar_reg.ttf
    
    - family: pr_ar_bold
      fonts:
        - asset: ./lib/assets/fonts/ar/pr_ar_bold.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "./lib/assets/img/logo.png"

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg